fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: check-ast   # checks Python syntax
    - id: check-json  # checks JSON syntax
#    - id: check-yaml  # checks YAML syntax
    - id: check-toml  # checks TOML syntax
    - id: end-of-file-fixer  # checks there is a newline at the end of the file
    - id: trailing-whitespace  # trims trailing whitespace
    - id: check-merge-conflict  # checks for no merge conflict strings
    - id: check-shebang-scripts-are-executable  # checks all shell scripts have executable permissions
    - id: mixed-line-ending  # normalizes line endings
    #- id: no-commit-to-branch  # prevents committing to main

- repo: https://github.com/psf/black
  rev: 22.6.0  # IMPORTANT: keep this aligned with the black version in pyproject.toml
  hooks:
  - id: black-jupyter

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.1.1'
  hooks:
  - id: mypy
    exclude: ^test/
    args: [--ignore-missing-imports]
    additional_dependencies: ['types-requests']

- repo: https://github.com/pycqa/pylint
  rev: 'v2.17.0'
  hooks:
  - id: pylint
    exclude: ^test/
    args: [
      "--disable=import-error"  # FIXME
    ]
